### ISSUE TITLE
overlaping events

### ISSUE THREAD

**Issue by nemezis007** [sproctor/php-calendar#138] opened 2015-08-28 10:05 UTC
At the beginning - thanks for a great job here - calendar is just great! I'm big fun!

Now to the problem or maybe future functionality that would be useful.
Is there a way to implement function that checks while adding new instance to calendar if there is already event of the same category at the same time, or the same category events that may overlap some hours? I would be great there is  message displayed, an error/warning message, while adding event that let user to decide: possible time overlap, are you fine with it or reschedule your event (apply/reschedule).

edit:
I would opt only for warning message (and options "go ahead/reedit"). Since I see that some categories may require coexistence in the same period of time...

Motivation for it.
I use the calendar to make clear scheduling of microscopes in our lab in institute.
I have divided set of the microscope to groups according to manufacturer (eg olympus, leica),
each group has categories which defines certain device one wants to use.
Since there are considerable amount of devices, every day on a calendar is usually full of instances and user (who are usual lazy bastards) see only the beginning time of event (without going to the details). While booking there were some issues that people haven't noticed till when other person uses it (eg till 4pm) and booked device while it was still  occupied by another person (eg from 3pm). 

I would be very grateful if implementing this would be considered. Thanks a lot
cheers, marcin

**Comment by sproctor** [comment] 2022-01-28 11:04
duplicate of #30

**Closed by sproctor** 2022-01-28 11:04 UTC
Labels: duplicate
